function stoTable = readSTO(stoFile)
% This function takes the .sto file generated by OpenSim when calculating
% inverse kinematics, usually named "_ik_model_marker_locations.sto", or a
% .sto file generated from inverse dynamics, and turns it into a table
% containing the same information. The resulting table will be identical in
% format to a table generated by readTRC(). The original .sto file contains
% the marker position over time of the model fit by inverse kinematics. 
% [stoTable] = readSTO(stoFile);
% 
% Returns: 
% stoTable - A table where each column is Header, a marker coordinate 
% (e.g. R_ASIS_x), or a joint moment, and each row is a different time. 

    assert(ischar(stoFile) && endsWith(lower(stoFile), '.sto'), 'This is not a STO file (*.sto).');
    data = importdata(stoFile);
    numData = data.data;
    newHeads = strrep(data.colheaders, '.', '_');
    newHeads{1} = 'Header'; % update 'time' to be Header
    stoTable = array2table(numData, 'VariableNames', newHeads);
end
