%% Example script detailing how Vicon functions can be used 

%% User starts with:
% static.c3d
% trial.c3d
%
% XML Template Files required for OpenSim
% scale.xml: template for scaling setup file 
%   model.osim: template for model file, referenced by scale.xml
%   markers.xml: description of marker placement, referenced by scale.xml
% ik.xml: template for inverse kinematics setup file
% 
% Examples of these files can be generated by OpenSim by using the GUI. 

staticC3D = './ExampleData/static_01.c3d';
c3dFile = './ExampleData/LevelGround_ccw_fast_01.c3d';
unscaledOsim = './ExampleData/KB_LowerBody.osim';
scaleXml = './ExampleData/ScaleSetup.xml';
ikXml = './ExampleData/IKSetup.xml';

outputDir = './ExampleData/generated';
staticTrc = fullfile(outputDir, 'static_01.trc');
scaledOsim = fullfile(outputDir, 'ExampleModel.osim');

% VerboseLevel - 0 (minimal), 1 (normal), 2 (debug mode)
verboseLevel = 1;

% ErrorThresholdLow - threshold of IK error above which bad marker data will be deleted. 
errorThresholdLow = 0.04;

% ErrorThresholdHigh - threshold of IK error above which marker data will be considered bad.
errorThresholdHigh = 0.06;

mkdir(outputDir);
%% Set up the static trial so that we can use a scaled model for IK 
% This repo uses a few different formats for handling marker position data:
% - A struct where each field is a marker, and the data is an nx3 double
% array of x,y,z coordinates, with n = number of frames. 
% - A table with 3*m+1 columns, with m = number of markers. Each column is
% a specific marker coordinate, and the first column is time in seconds. 
% - A *.trc ASCII file used for OpenSim, structured similarly to the table,
% with another column for the frame. 
% - A *.mat binary file with either the struct or the table saved as the
% only variable in it. 
% For ease of use, any of these formats can be inputted into any function
% that takes marker data, and it will be automatically converted to the
% most appropriate form through the function Osim.interpret. 
staticMarkerData = Vicon.ExtractMarkers(staticC3D); % staticMarkerData is a struct
gapInfo = Vicon.findGaps(staticMarkerData);
nGaps = sum(structfun(@numel, gapInfo));

if nGaps ~= 0
    % If the static trial has gaps, then fill them and use the unscaled
    % osim file for segment info (to determine donors). This is not
    % iterative gap filling, as iterative gap filling would require a
    % scaled model, which is what we are trying to get in this section.
    % This uses only interpolation methods. 
    staticMarkerData = Vicon.GapFill(staticMarkerData, unscaledOsim);
end
Osim.Scale(staticMarkerData, scaleXml, scaledOsim);
clc;
%% Gap Fill a C3D file
% show the number of gaps present at the beginning
fprintf('Gap info of file: [nGapsx2 double]\n');
markerStruct = Vicon.ExtractMarkers(c3dFile);
disp(Vicon.findGaps(markerStruct))

[markerStruct, errorTable] = Vicon.IterativeGapFilling(c3dFile, ikXml, ...
    'VerboseLevel', verboseLevel, ...
    'ErrorThresholdHigh', errorThresholdHigh, ...
    'ErrorThresholdLow', errorThresholdLow, ...
    'MaxIterations', 2);
% markerStruct and errorTable are saved to OutputDir

% view IK marker errors, more info in Osim example script
Osim.viewIKError(errorTable);

% display the gaps in each marker, there should be none
fprintf('Gap info of file after gap filling:\n');
disp(Vicon.findGaps(markerStruct))

fprintf('Look at the history in the command window to see gap info and gap filling results.\n');

%% Continue with the gap filled data
% write back to a c3d
fprintf('Writing .c3d file...\n');
[~, trialname, ~] = fileparts(c3dFile);
filledC3D = fullfile(outputDir, [trialname '_filled.c3d']);
Vicon.markers2C3D(markerStruct, c3dFile, filledC3D);

% create a trc file 
fprintf('Writing .trc file...\n');
trcFile = Osim.markers2TRC(markerStruct, 'FilePath', fullfile(outputDir, trialname), 'FilterFreq', 6);

% create an mot file
fprintf('Writing .mot file...\n');
motData = Vicon.C3DtoMOT(filledC3D, 'CombinedForceplates', 5:6, 'FilterFreq', 15, 'DeviceNames', [compose('Treadmill_%c', 'RL'), compose('Amp%d', 1:6), {'Combined'}]);
Osim.writeMOT(motData, 'FilePath', fullfile(outputDir, trialname));
